Hw03 frequency analysis
BBeRsErKeRR/otus-golang-hw pull request #3
Opened 2022-12-18 13:30 UTC by BBeRsErKeRR

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-12-18 15:33 UTC, dshemin requested changes

2022-12-18 15:33 UTC, dshemin commented on hw03_frequency_analysis/top.go
> +	if input != "" {
Важно:

Более чистым и правильным решением будет проверить равна ли переменная пустой строке и вернуть nil из функции и потом обрабатывать строку, чем так. Появляется излишняя вложенность.

2022-12-18 15:33 UTC, dshemin commented on hw03_frequency_analysis/top.go
> +		re := regexp.MustCompile(`\s+(-\s+)*`)
Совет:

Компиляция регулярок - дорогой процесс, Если регулярки статичные, то лучше их компиляцию выносить в приватные переменные пакета.

2022-12-18 15:33 UTC, dshemin commented on hw03_frequency_analysis/top.go
> +		if len(words) >= 10 {
Критично:

Наша функция не будет работать если у нас в предложении меньше 10 слов? Если обратите внимание на пример в задании, там выводится топ 7 слов.

2022-12-18 15:33 UTC, dshemin commented on hw03_frequency_analysis/top.go
> +		replace := regexp.MustCompile(`[,.!:"']+`)
Важно:

Для простых реплейсов, а у нас тут простая замена, лучше использовать методы из пакета strings. Более эффективное решение.

2022-12-18 15:33 UTC, dshemin commented on hw03_frequency_analysis/top_test.go
> +var taskWithAsteriskIsCompleted = true
Критично:

Нет дополнительных юнит-тестов, это -4 бала. Добавьте тесты на краевые случаи, например если у нас предложение всего из одного слова.

2022-12-19 13:44 UTC, BBeRsErKeRR commented on hw03_frequency_analysis/top_test.go
> +var taskWithAsteriskIsCompleted = true
Добавил доп unit тесты

2022-12-19 13:46 UTC, BBeRsErKeRR commented on hw03_frequency_analysis/top.go
> +		replace := regexp.MustCompile(`[,.!:"']+`)
Предполагалось дополнительно решить задачку с апострофами, но пакет `"regexp"` не поддерживает lookahead/lookbehind.
Переписал на replacer.

2022-12-19 13:47 UTC, BBeRsErKeRR commented on hw03_frequency_analysis/top.go
> +		if len(words) >= 10 {
Внес исправления

2022-12-19 14:40 UTC, dshemin approved these changes

2023-01-04 02:32 UTC, merged