Hw09 struct validator
BBeRsErKeRR/otus-golang-hw pull request #9
Opened 2023-02-26 03:16 UTC by BBeRsErKeRR

## Домашнее задание №9 «Валидатор структур»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 3 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2023-02-26 03:41 UTC, dshemin requested changes

2023-02-26 03:41 UTC, dshemin commented on hw09_struct_validator/validator_test.go
>  			_ = tt
Важно:

Нужно удалить.

2023-02-26 03:41 UTC, dshemin commented on hw09_struct_validator/validator_test.go
> +			_ = tt
Важно:

Это не нужно.

2023-02-26 03:41 UTC, dshemin commented on hw09_struct_validator/validator.go
> +			fE := v.validateField(fieldDetail.Name, valF.Interface(), fieldDetail.Tag)
Критично:

> Таким образом, нужно накопить все ошибки валидации, а не прерывать валидацию на первой ошибке.

У нас сейчас валидация прервётся на первом не валидном поле.

2023-02-26 03:41 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	if tag.Get("validate") != "" {
Важно:

Советую инвертировать условие, чем меньше вложенность, тем легче читать.

2023-02-26 03:41 UTC, dshemin commented on hw09_struct_validator/validator.go
> +		validate, ok := tag.Lookup("validate")
Важно:

Зачем нам вызывать tag.Get, если мы тут получаем ok который говорит, установлено ли значение или нет?

2023-02-27 06:47 UTC, dshemin requested changes

2023-02-27 06:47 UTC, dshemin commented on hw09_struct_validator/validator_test.go
> +var i *int
Важно:

Что это за переменная глобальная? Она нам точно нужна?

2023-02-27 06:47 UTC, dshemin commented on hw09_struct_validator/validator.go
> +			fE := v.validateField(fieldDetail.Name, valF.Interface(), fieldDetail.Tag)
Обратите внимание на этот комментарий.

2023-02-27 07:24 UTC, BBeRsErKeRR commented on hw09_struct_validator/validator.go
> +			fE := v.validateField(fieldDetail.Name, valF.Interface(), fieldDetail.Tag)
Исходя из условия:
>Функция может возвращать
> - или программную ошибку, произошедшую во время валидации;
> - или `ValidationErrors` - ошибку, являющуюся слайсом структур, содержащих имя поля и ошибку его валидации.

В случае с не валидным тегом validate реализация предполагает, что нам достаточно вернуть  `программную ошибку, произошедшую во время валидации`.
Зачем нам накапливать все ошибки валидации, которые, исходя из условия, мы не будем возвращать?

2023-02-27 07:27 UTC, dshemin commented on hw09_struct_validator/validator.go
> +			fE := v.validateField(fieldDetail.Name, valF.Interface(), fieldDetail.Tag)
Вы путаете. Есть ошибки программы, когда кто-то навесил валидацию `len` на поле с числом. И есть ошибка валидации, когда валидатор сконфигурирован верно, но данные в рантайме не те.

2023-02-27 08:18 UTC, BBeRsErKeRR commented on hw09_struct_validator/validator.go
> +			fE := v.validateField(fieldDetail.Name, valF.Interface(), fieldDetail.Tag)
Код именно так и работает. Требуется ли накапливать срез программных ошибок?
P.S. Дополнительно добавил тесты на несколько ошибок, а также обработку не существующих или пустых внутренних тегов как программную ошибку.

2023-02-28 08:55 UTC, BBeRsErKeRR commented on hw09_struct_validator/validator.go
> +			fE := v.validateField(fieldDetail.Name, valF.Interface(), fieldDetail.Tag)
Можете уточнить, что конкретно сделано не корректно, т.к. я не понмаю где ошибка?

2023-03-02 01:11 UTC, dshemin requested changes

2023-03-02 01:11 UTC, dshemin commented on hw09_struct_validator/validator.go
> +			fE := v.validateField(fieldDetail.Name, valF.Interface(), fieldDetail.Tag)
Смотрите, у нас есть структура с 2 полями. В обоих ошибка валидации, код должен вернуть ошибки в обоих полях. В вашем текущем коде, вы собираете все ошибки для ОДНОГО поля, а надо для ВСЕХ. Т.е. не прерывать цикл тут пока не накопите все ошибки. Но только ошибки валидации, програмные ошибки, исходя из текста задания, накапливать, сразу возвращать.

2023-03-02 03:06 UTC, BBeRsErKeRR commented on hw09_struct_validator/validator.go
> +			fE := v.validateField(fieldDetail.Name, valF.Interface(), fieldDetail.Tag)
Это не так. Собираются все ошибки для всех полей, через функцию `appendError`

```go
func (v *Validator) appendError(name string, e error) {
	validationError := ValidationError{}
	validationError.Field = name
	validationError.Err = e
	v.validationErrors = append(v.validationErrors, validationError)
}
```
Пример для string:

```go
func (v *Validator) validateString(name, value string, tag map[string]string) error {
	var isRunning bool
	count := tag["len"]
	if count != "" {
		isRunning = true
		countInt, err := strconv.Atoi(count)
		if err != nil {
			return err
		}
		if countInt < len(value) {
                       // APPEND VALIDATION ERROR
			v.appendError(name, errorValidateStringLength)
		}
	}
...
```

А в конце мы уже получаем ошибки:
```go
valErrors := validator.getErrors()
	if len(valErrors) > 0 {
		return valErrors
	}
```

Дополнительно дополнил тест на проверку всех допустимых ошибок в структуре `User`

2023-03-02 06:34 UTC, BBeRsErKeRR commented on hw09_struct_validator/validator_test.go
> +		},
Тест на проверку нескольких ошибок валидации в структуре

2023-03-03 04:46 UTC, dshemin approved these changes

2023-03-03 04:46 UTC, dshemin commented on hw09_struct_validator/validator.go
> +			fE := v.validateField(fieldDetail.Name, valF.Interface(), fieldDetail.Tag)
Теперь увидел, не очень очевидное решение.

2023-03-03 07:54 UTC, merged